language: minimal
os: linux

services:
- docker

install:
- docker pull golang
- |
    function assert_redirect() {
        GOT=`curl -w "%{url_effective}\n" -I -L -s -S "$1" -o /dev/null`;
        EXPECTED="$2";
        
        if [ "$GOT" == "$EXPECTED" ]; then
            echo -e "\033[0;32m[PASS]\033[0m $1 => $GOT";
            return 0;
        else
            echo -e "\033[0;31m[FAIL]\033[0m $1 => $GOT (expected $EXPECTED)"; 
            return 1;
        fi;
    }

script:
- docker build -t tkw1536/tr .
- docker run -d --name=smoke -p 8080:80 -e TARGET=https://example.com/subdirectory tkw1536/tr
- sleep 10
- assert_redirect "http://localhost:8080/" "https://example.com/subdirectory/" 
- assert_redirect "http://localhost:8080/path/" "https://example.com/subdirectory/path/"

after_script:
- docker stop smoke

