name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Check that 'gofmt' has been run
        run: test -z $(gofmt -l .)
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Run 'go test'
        run: go test -v ./...
  dockertest:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
        - name: Run 'test.sh'
          run: bash test.sh ghcr.io/tkw1536/tr:latest
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Run 'go build'
        run: go build ./cmd/redirect
      - name: Upload executables
        uses: actions/upload-artifact@v2
        with:
          name: Binaries
          path: redirect
